# Inspired by https://github.com/firebase/flutterfire/blob/master/melos.yaml
name: tvarkau-lietuva-frontend
repository: https://github.com/AplinkosMinisterija/tvarkau-lietuva-frontend

packages:
  - api_client
  - core
  - core_ui
  - features/**

scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.

  analyze:
    # We are setting the concurrency to 1 because a higher concurrency can crash
    # the analysis server on low performance machines (like GitHub Actions).
    run: dart analyze .
    exec:
      concurrency: 1
    description: |
      Run `dart analyze` in all packages.
       - Note: you can also rely on your IDEs Dart Analysis / Issues window.

  format:
    run: |
      dart pub global run flutter_plugin_tools format
    description: |
      Formats the code of all packages.
       - Requires `flutter_plugin_tools` (`pub global activate flutter_plugin_tools`).
       - Requires `git`.

  # Additional cleanup lifecycle script, executed when `melos clean` is run.
  postclean: >
    melos exec -c 6 -- "flutter clean"
