name: tvarkau_lietuva
description: Tvarkau Lietuva programele
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <3.13.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  core:
    path: core
  core_ui:
    path: core_ui
  dashboard:
    path: features/dashboard
  admin:
    path: features/admin
  api_client:
    path: api_client

  go_router: ^13.2.0
  sentry_flutter: ^7.10.1
  openapi_generator_annotations: ^5.0.2
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  openapi_generator: ^5.0.2
  flutter_native_splash: ^2.3.9
  melos: ^4.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/svg/
    - assets/icons/marker_pins/

flutter_native_splash:
  color: "#396154"
  image: "web/icons/android-chrome-512x512.png"
  android: false
  ios: false
  web: true