name: core
description: core module for the project
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.13.0'

dependencies:
  flutter:
    sdk: flutter
  api_client:
    path: ../api_client

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^7.3.3
  flutter_dotenv: ^5.0.2
  google_fonts: ^4.0.0
  url_launcher: ^6.1.11
  g_recaptcha_v3: ^0.0.5
  webviewx_plus: ^0.3.3
  image: ^4.0.17
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0
  dio: ^5.0.0
  built_collection: ^5.1.1
  loading_animation_widget: ^1.2.0+4
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.core
    iosBundleIdentifier: com.example.core
