name: core
description: core module for the project
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.13.0'

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data
  domain:
    path: ../domain
  navigation:
    path: ../navigation

  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^7.3.3
  flutter_dotenv: ^5.0.2
  google_fonts: ^4.0.0
  url_launcher: ^6.1.11
  g_recaptcha_v3: ^0.0.5
  webviewx_plus: ^0.3.3
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.core
    iosBundleIdentifier: com.example.core
