name: admin
description: Admin package
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.2.0 <3.13.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../../core
  core_ui:
    path: ../../core_ui
  api_client:
    path: ../../api_client

  flutter_bloc: ^8.1.4
  loading_animation_widget: ^1.2.0+4
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.3
  auto_size_text: ^3.0.0
  aad_oauth: ^1.0.1
  dropdown_button2: ^2.3.9
  go_router: ^13.2.0
  syncfusion_flutter_core: 24.1.41
  syncfusion_flutter_datagrid: 24.1.41
  collection: ^1.17.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
