name: core_ui
description: core UI module for the application
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <3.13.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  core:
    path: ../core
  api_client:
    path: ../api_client


  cupertino_icons: ^1.0.2
  flutter_cupertino_datetime_picker: ^3.0.0
  google_fonts: ^4.0.0
  flutter_svg: ^2.0.9
  flutter_map: ^6.1.0
  flutter_map_marker_cluster: ^1.3.4
  latlong2: ^0.9.0
  url_launcher: ^6.2.3
  flutter_map_location_marker: ^8.0.3
  loading_animation_widget: ^1.2.0+4
  auto_size_text: ^3.0.0
  universal_io: ^2.2.0
  gallery_image_viewer: ^1.2.0
  flutter_staggered_grid_view: ^0.6.2
  pointer_interceptor: ^0.9.3+4
  syncfusion_flutter_datagrid: ^24.1.46
  http_parser: ^4.0.2
  proj4dart: ^2.1.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - ../assets/icons/
    - ../assets/svg/

  module:
    androidX: true
    androidPackage: com.example.core_ui
    iosBundleIdentifier: com.example.coreUi
