name: core_ui
description: core UI module for the application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <3.13.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  core:
    path: ../core
  api_client:
    path: ../api_client

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: 2.0.5
  loading_animation_widget: ^1.2.0+4
  google_maps_flutter: ^2.5.3
  auto_size_text: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  pointer_interceptor: ^0.10.1
  syncfusion_flutter_core: 24.1.41
  syncfusion_flutter_datagrid: 24.1.41
  animated_custom_dropdown: ^3.0.0
  latlong2: ^0.9.1
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - ../assets/icons/
    - ../assets/svg/

  module:
    androidX: true
    androidPackage: com.example.core_ui
    iosBundleIdentifier: com.example.coreUi
