name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  dart-analyzer:
    name: Dart analyze
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Analyze project
        run: flutter analyze > flutter-lints.txt || true

      - name: Flutter Analyze to SARIF
        uses: advanced-security/dart-analyzer-sarif@v1
        with:
          input: flutter-lints.txt
          output: flutter-lints.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: flutter-lints.sarif
          category: flutter-lints
