name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  dart-analyzer:
    name: Dart analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - run: flutter pub get

      - run: flutter analyze --write=flutter_analyze.log --no-fatal-infos

      - if: ${{ !cancelled() }}
        uses: yorifuji/flutter-analyze-commenter@v1
        with:
          analyze-log: flutter_analyze.log    # file path for analyze log
