name: Continuous integration

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  dart-analyzer:
    name: Dart analyze
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Analyze project
        run: flutter analyze
